# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_questionanswer_userquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='ChoiceQuestion',
        ),
    ]
